# Generated by Django 5.0.6 on 2024-07-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_student_graduation_date_student_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='research_chapters/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.student')),
            ],
        ),
    ]
