# Generated by Django 5.0.6 on 2024-07-14 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_researchproject_casestudy_researchproject_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myweb.supervisor'),
        ),
    ]
