# Generated by Django 5.0.6 on 2024-07-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_researchchapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchchapter',
            name='chapter_name',
        ),
        migrations.AddField(
            model_name='researchchapter',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchchapter',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myweb.student'),
        ),
    ]
