# Generated by Django 5.0.6 on 2024-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_alter_student_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchproject',
            old_name='casestudy',
            new_name='casestudy_1',
        ),
        migrations.RenameField(
            model_name='researchproject',
            old_name='district',
            new_name='district_1',
        ),
        migrations.RenameField(
            model_name='researchproject',
            old_name='title',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='casestudy_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='casestudy_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='district_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='district_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='selected_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='title_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='title_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
