# Generated by Django 5.0.6 on 2024-07-14 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_rename_casestudy_researchproject_casestudy_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='research_project',
        ),
        migrations.AddField(
            model_name='student',
            name='selected_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='myweb.researchproject'),
        ),
    ]
