# Generated by Django 5.0.6 on 2024-07-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_remove_researchchapter_chapter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_file', models.FileField(upload_to='research_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ResearchChapter',
        ),
    ]
