# Generated by Django 5.0.6 on 2024-07-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_studentresearchfile_delete_researchchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='research_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentResearchFile',
        ),
    ]
