# Generated by Django 5.0.6 on 2024-07-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_remove_student_research_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='selected_title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='myweb.researchproject'),
        ),
    ]
