# Generated by Django 5.0.6 on 2024-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_researchfile_delete_studentresearchfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='Contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
