# Generated by Django 5.0.6 on 2024-07-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_alter_student_selected_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='selected_title',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='myweb.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='selected_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='myweb.researchproject'),
        ),
    ]
