# Generated by Django 5.0.6 on 2024-07-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_remove_researchproject_selected_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='research_projects',
            field=models.ManyToManyField(blank=True, to='myweb.researchproject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='selected_title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='myweb.researchproject'),
        ),
    ]
