# Generated by Django 5.0.6 on 2024-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_supervisor_contact_supervisor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Graduation_date',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
