# Generated by Django 5.1 on 2024-09-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_remove_researchproject_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='research_projects',
            new_name='research_project',
        ),
    ]
