# Generated by Django 5.0.6 on 2024-07-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_rename_graduation_date_student_graduation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Graduation_date',
            new_name='graduation_date',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
