# Generated by Django 5.0.6 on 2024-07-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_rename_graduation_date_student_graduation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submitted_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_file', to='myweb.researchfile'),
        ),
        migrations.AlterField(
            model_name='researchfile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_files', to='myweb.student'),
        ),
    ]
