# Generated by Django 5.0.6 on 2024-07-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_student_submitted_file_alter_researchfile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='submitted_file',
        ),
        migrations.AlterField(
            model_name='researchfile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.student'),
        ),
    ]
