# Generated by Django 5.1 on 2024-09-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myweb', '0012_alter_candidate_student_alter_student_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_permissions_set', to='auth.permission'),
        ),
    ]
