# Generated by Django 5.1 on 2024-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_alter_student_groups_alter_student_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.CharField(max_length=255),
        ),
    ]
