# Generated by Django 5.0.6 on 2024-07-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
    ]
