# Generated by Django 5.1 on 2024-09-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_vote_position_alter_vote_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.candidate'),
        ),
    ]
