# Generated by Django 5.1 on 2024-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_remove_vote_position_alter_vote_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='student',
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
